<!DOCTYPE html>
<html lang="en"><head>
<script src="test_2_082025_files/libs/clipboard/clipboard.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tabby.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/popper.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="test_2_082025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content=" Lesley Chapman Hannah, Ph.D., M.S. College of Graduate Studies Northeast Ohio Medical University">
  <title>Statistical Estimation: Evaluating Bias, Variance, and Sampling Behavior</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h2 style="color: #2A76DD;" class="title">Statistical Estimation: Evaluating Bias, Variance, and Sampling Behavior</h2>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div style="font-size:20px;" class="quarto-title-author-name">
<br><br><span style="font-size:25px;"><strong>Lesley Chapman Hannah, Ph.D., M.S.</strong></span><br>College of Graduate Studies<br>Northeast Ohio Medical University 
</div>
</div>
</div>

</section>
<section class="slide level2">

<h3 id="overview">Overview</h3>
<div style="font-size:0.5em">
<ul>
<li><p>understanding how to identify ideal estimators that target a specific quantity and with less variation per sample</p></li>
<li><p>understand point estimates - sample-based value for a population parameter</p></li>
<li><p>characterize bias - description of whether an estimator is centered on the truth across repeated samples</p></li>
<li><p>discuss variance and standard error - descriptors of repeated-sampling</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="central-theme">Central Theme</h3>
<div style="font-size:0.5em">
<p><strong>Recap</strong>:</p>
<ul>
<li>established that a sample statistic can be used to estimate an unknown population quantity</li>
<li><code>estimator</code> : defines how the data are used to approximate the population quantity [i.e.: mean, sample proportion, regression coefficient]</li>
</ul>
<p><strong>Current Aim</strong>: Evaluate the quality of the estimator</p>
<p>Indicators of a good estimator:</p>
<ol type="1">
<li>target the correct population quantity</li>
<li>vary as little as possible across repeated samples</li>
</ol>
<p>Estimator checks:</p>
<ul>
<li><p>determine whether the estimator is centered on the target parameter</p></li>
<li><p>observe how widely the estimator varies across repeated samples</p></li>
<li><p>determine whether the design assumptions needed for that estimator are plausible</p></li>
<li><p>here the <strong>sampling distribution</strong> is a key tool for judging estimator quality</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="point-estimation">Point Estimation</h3>
<div style="font-size:0.5em">
<ul>
<li><p><strong>point estimate</strong> : single numerical value computed from sample data to approximate an unknown population parameter</p></li>
<li><p>interpretable quantities derived from data [i.e.: average treatment effects, disease prevalence, or risk differences] and serve as the basis for confidence intervals, hypothesis tests</p></li>
</ul>
<p>Two examples include:</p>
<p><strong>Sample Mean</strong></p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
\]</span></p>
<p>and</p>
<p><strong>Sample Proportion</strong></p>
<p><span class="math display">\[
\hat{p} = \frac{x}{n}
\]</span></p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span>: sample mean <span class="math inline">\(\rightarrow\)</span> estimate of a population mean <span class="math inline">\(\mu\)</span></li>
<li><span class="math inline">\(x_i\)</span>: the value for the <span class="math inline">\(i\)</span>th sampled observation</li>
<li><span class="math inline">\(n\)</span>: sample size</li>
<li><span class="math inline">\(\hat{p}\)</span>: sample proportion <span class="math inline">\(\rightarrow\)</span> estimate of a population proportion <span class="math inline">\(p\)</span></li>
<li><span class="math inline">\(x\)</span>: number of observations in the sample with the characteristic of interest</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="estimation-in-biomedical-inference">Estimation in Biomedical Inference</h3>
<div style="font-size:0.6em">
<ul>
<li><p>estimation is used to quantify key quantities such as average biomarker level, disease prevalence, treatment response, or average processing time</p></li>
<li><p>biased estimator can systematically misstate the underlying biology or clinical burden</p></li>
<li><p>highly variable estimator can produce unstable results that differ substantially from one study sample to another</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="common-failures-in-statistical-estimation">Common Failures in Statistical Estimation</h3>
<div style="font-size:0.6em">
<p>estimator can fail [provide a poor estimation for the true population parameter] in two ways:</p>
<ul>
<li><p>exhibiting systematic deviation from the target <a href="#/bias">bias</a></p></li>
<li><p>displaying excessive sampling variability [high variance across repeated samples</p></li>
<li><p>estimator can fail because it is <strong>biased</strong>: estimator systematically misses the target</p></li>
<li><p>estimator lacks accuracy if it does not target the true parameter on average <a href="#/bias">bias</a></p></li>
<li><p>estimator can be <strong>too variable</strong>: if estimator is centered correctly after multiple samples each individual sample-based estimates move around too much</p></li>
<li><p>estimator lacks precision if it is too variable across samples [variance]</p></li>
</ul>
<p>The three panels therefore represent three distinct cases:</p>
<ul>
<li><strong>biased estimator</strong>: sampling distribution is shifted away from the true value [systematic error]</li>
<li><strong>unbiased imprecise estimator</strong>: centered at the true value but with large spread [high variability]</li>
<li><strong>unbiased and precise estimator</strong>: centered at the true value with small spread [low variability]</li>
</ul>
<p>good estimation requires both correct centering [low bias] and tight concentration [low variance]</p>
</div>
</section>
<section id="bias" class="slide level2">
<h2>Bias</h2>
<div style="font-size:0.6em">
<p><code>Bias</code> measures systematic deviation from the true parameter:</p>
<p><span class="math display">\[
\operatorname{Bias}(\hat{\theta}) = E(\hat{\theta}) - \theta
\]</span></p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(\hat{\theta}\)</span>: estimator</p></li>
<li><p><span class="math inline">\(E(\hat{\theta})\)</span>: expected value or average of the estimator across repeated samples</p></li>
<li><p><span class="math inline">\(\theta\)</span>: true population parameter being estimated</p></li>
<li><p>bias = zero : estimator is <strong>unbiased</strong></p></li>
<li><p>bias = negative/positive value : average falls above or below the true parameter <span class="math inline">\(\rightarrow\)</span> estimator is <strong>biased</strong></p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="unbiased-and-biased-estimators">Unbiased and Biased Estimators</h3>
<div style="font-size:0.6em">
<ul>
<li><strong>unbiased statistic</strong> :
<ul>
<li>sampling distribution centered at the true parameter</li>
<li>over many repeated samples estimate does not overestimate or underestimate the target</li>
</ul></li>
<li><strong>biased statistic</strong> :
<ul>
<li>estimator whose sampling distribution is centered away from the true parameter
<ul>
<li>sampling distribution centered away from the target</li>
</ul></li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="precision-and-variance">Precision and Variance</h3>
<div style="font-size:0.6em">
<ul>
<li><code>precision</code> : describes how tightly an estimator clusters</li>
<li>estimator variance: expected squared distance between the estimator and the repeated-sample mean</li>
</ul>
<p>Variance Formula</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{\theta}) = E\left[(\hat{\theta} - E(\hat{\theta}))^2\right]
\]</span></p>
<ul>
<li><p><span class="math inline">\(\operatorname{Var}(\hat{\theta})\)</span>: variance of the estimator</p></li>
<li><p><span class="math inline">\(\hat{\theta}\)</span>: random variable [estimator]</p></li>
<li><p><span class="math inline">\(E(\hat{\theta})\)</span>: center of the estimator across multiple samples</p></li>
<li><p><code>smaller variance</code>: indicates that the estimator is more tightly concentrated around its expected value across repeated samples</p></li>
<li><p><code>larger variance</code> : indicates that the estimator is more dispersed across repeated samples</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="accuracy-versus-precision">Accuracy Versus Precision</h3>
<div style="font-size:0.6em">
<p><strong>accuracy</strong> and <strong>precision</strong>: statistical properties that describe how an estimator’s sampling distribution relates to the true parameter value in terms of its center and spread</p>
<ul>
<li><strong>accuracy <a href="#/bias">bias</a></strong> : metric to describe how close the center of the estimator’s sampling distribution is to the true parameter value</li>
</ul>
<p>Example: accurate estimator is centered at the target in repeated sampling</p>
<ul>
<li><strong>precision [variability]</strong>: metric describing the spread of the estimator’s sampling distribution</li>
</ul>
<p>Example: precise estimator has less sampling variability <span class="math inline">\(\rightarrow\)</span> repeated samples produce estimates that are more tightly clustered around the center of the distribution</p>
</div>
</section>
<section id="research-question-background-chronic-kidney-disease" class="slide level2">
<h2>Research Question Background: Chronic Kidney Disease</h2>
<div style="font-size:0.58em">
<ul>
<li>chronic kidney disease (CKD): sustained reduction in kidney function and is a major contributor to morbidity and mortality at the population level</li>
<li>United States approximately 14–15% of adults are estimated to have CKD</li>
<li>kidney function is quantified using estimated glomerular filtration rate (eGFR) - continuous measure derived from serum creatinine and patient characteristics that approximates filtration capacity</li>
</ul>
<p>estimated glomerular filtration rate [eGFR]</p>
<ul>
<li>≥ 90 → generally considered normal kidney function</li>
<li>60–89 → mildly reduced kidney function</li>
<li>&lt; 60 → clinically meaningful reduction, consistent with chronic kidney disease (CKD)</li>
</ul>
</div>
</section>
<section id="research-aim" class="slide level2">
<h2>Research Aim</h2>
<div style="font-size:0.58em">
<p>Research goal(s) estimate two population quantities:</p>
<ul>
<li>population mean eGFR</li>
<li>population proportion with CKD</li>
</ul>
<p>Approach</p>
<ol type="1">
<li>create a simulated biomedical population<br>
</li>
<li>generate simulated true population quantities</li>
<li>draw study samples from that population<br>
</li>
<li>compute point estimates from each sample<br>
</li>
<li>examine repeated samples to study sampling distributions, bias, variance, precision</li>
</ol>
</div>
</section>
<section id="simulated-population-dataset" class="slide level2">
<h2>Simulated Population Dataset</h2>
<div style="font-size:0.50em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
     id   age systolic_bp  uacr  egfr   ckd
  &lt;int&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  52.3        132.  37.8  68.7     0
2     2  56.2        157.  14.4  77.1     0
3     3  77.7        127.  82.9  45.1     1
4     4  59.8        127.  13.8  58.7     1
5     5  60.6        135.  26.5  65.1     0
6     6  79.6        149.  25.1  56.7     1</code></pre>
</div>
</div>
<p><strong>Overview</strong></p>
<ul>
<li><p>one row per individual in the population</p></li>
<li><p><strong>eGFR [estimated glomerular filtration rate]</strong>:</p>
<ul>
<li>clinical measure of kidney function, expressed in mL/min/1.73 m²</li>
<li>reflects how effectively the kidneys filter waste from the blood</li>
</ul></li>
<li><p><strong>CKD [chronic kidney disease]</strong> :</p>
<ul>
<li>long-term condition characterized by reduced kidney function</li>
<li>binary indicator equal to 1 when eGFR is below 60 <span class="math inline">\(\rightarrow\)</span> indicator of the presence of disease</li>
</ul></li>
<li><p><strong>age</strong>: clinical predictor associated with physiologic decline in kidney function<br>
</p></li>
<li><p><strong>systolic_bp</strong>: blood pressure measure included because elevated blood pressure is clinically relevant to kidney disease risk<br>
</p></li>
<li><p><strong>uacr</strong>: urine albumin-to-creatinine ratio additional kidney function biomarker</p></li>
</ul>
</div>
</section>
<section id="population-quantities" class="slide level2">
<h2>Population Quantities</h2>
<div style="font-size:0.58em">
<p>Here we define the target quantities in the population:</p>
<ul>
<li><p>population mean eGFR</p></li>
<li><p>population proportion with CKD</p></li>
<li><p><strong>population parameters</strong> that the estimators are trying to recover</p></li>
<li><p>true average kidney function in the full population [mean eGFR]</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 61.39921</code></pre>
</div>
</div>
<ul>
<li>true proportion of individuals classified as having CKD in this simulated population</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>true_prop_ckd <span class="ot">&lt;-</span> <span class="fu">mean</span>(population<span class="sc">$</span>ckd)</span>
<span id="cb3-2"><a href=""></a></span>
<span id="cb3-3"><a href=""></a>true_prop_ckd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.45818</code></pre>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="determine-point-estimates">Determine Point Estimates</h3>
<div style="font-size:0.58em">
<p>Following point estimates approximate the population quantity using only the information observed in the sample:</p>
<ul>
<li><strong>sample mean eGFR</strong> : point estimate because that reduces all observed eGFR values in the sample to one number that represents the population mean kidney function</li>
<li><strong>sample proportion with CKD</strong> : point estimate because that reduces all observed disease indicators a single value that represents the population prevalence of CKD</li>
</ul>
<p>Multiple individual observations are summarized in a single value representing the corresponding population parameter</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  sample_mean_egfr sample_prop_ckd
             &lt;dbl&gt;           &lt;dbl&gt;
1             60.6           0.513</code></pre>
</div>
</div>
<ul>
<li><p>sample mean eGFR = 60.6 : average kidney function among the individuals who were included in the sample</p></li>
<li><p>sample proportion with CKD = 0.513 : 51.3% of individuals in this sample meet the CKD definition (eGFR &lt; 60)</p></li>
<li><p>estimates are close to the population values, the sample happened to produce estimates near true population parameters</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="sampling-distribution-of-the-sample-mean">Sampling Distribution of the Sample Mean</h3>
<div style="font-size:0.57em">
<ul>
<li><p><strong>sampling distribution</strong> : distribution of an estimator across many repeated samples of the same size</p></li>
<li><p>distribution shows both the center and the spread of the estimator</p></li>
<li><p>2,000 independent study samples of size 150 drawn randomly from the population - sample mean eGFR is calculated for each sample</p></li>
<li><p><code>avg_estimate</code> : repeated-sample average of the estimator <a href="#/bias">bias</a></p></li>
<li><p><code>sd_of_estimates</code> : empirical standard deviation of the estimates[sampling variability]</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  avg_estimate sd_of_estimates
         &lt;dbl&gt;           &lt;dbl&gt;
1         61.4            1.08</code></pre>
</div>
</div>
<ul>
<li>average of the sample means across many repeated samples : 61.04</li>
<li>standard deviation of the sample means : 1.08</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="sampling-distribution-of-the-sample-mean-1">Sampling Distribution of the Sample Mean</h3>
<div style="font-size:0.50em">
<ul>
<li><p>histogram shows the distribution of sample mean estimates across repeated samples</p></li>
<li><p>dashed line marks the true population mean eGFR</p></li>
<li><p>estimator is performing well <span class="math inline">\(\rightarrow\)</span> distribution is centered near the dashed line</p></li>
<li><p>narrower distribution indicates increased precision</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="unbiased-and-biased-estimators-1" class="slide level2">
<h2>Unbiased and Biased Estimators</h2>
<div style="font-size:0.55em">
<p>Goal: compare the following two estimators of mean eGFR:</p>
<ul>
<li>estimator based on a simple random sample from the full population<br>
</li>
<li>biased estimator based on a truncated sampling frame that excludes individuals with lower eGFR values</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  estimator            repeated_sample_mean   bias
  &lt;chr&gt;                               &lt;dbl&gt;  &lt;dbl&gt;
1 Unbiased sample mean                 61.4 0.0163
2 Biased sample mean                   64.2 2.79  </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p>unbiased sample mean 61.4 - average of the sample mean estimates across many repeated random samples from the full population with 0.0163 bias</p></li>
<li><p>low bias indicates that on average the estimator recovers the true population mean with essentially no systematic error</p></li>
<li><p>64.2 : average of the sample mean estimates across repeated samples drawn from the truncated population [i.e.: where lower eGFR individuals are excluded]</p></li>
<li><p>2.79 : bias - estimator overestimates the true population mean by about 2.79 units on average</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="unbiased-and-biased-estimators-2">Unbiased and Biased Estimators</h3>

<img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"><div style="font-size:0.50em">
<p><strong>Interpretation</strong></p>
<ul>
<li>unbiased estimator : centered near the true mean eGFR</li>
<li>biased estimator : shifted upward away from the target because lower eGFR individuals were excluded before sampling</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="precision-and-sample-size">Precision and Sample Size</h3>
<div style="font-size:0.55em">
<ul>
<li>compare sample estimator across different sample sizes</li>
<li>table shows the same estimator [sample mean eGFR—behaves across repeated samples] as the sample size increases</li>
</ul>
<p>Note: target population mean changes very little while the precision of the estimator changes</p>
<ul>
<li><code>n</code> : sample size used for each draw</li>
<li><code>mean_estimate</code> : average of the sample means across many repeated samples</li>
<li><code>variance_estimate</code> and <code>sd_estimate</code> : quantify how much the sample mean varies from sample to sample</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
      n mean_estimate variance_estimate sd_estimate
  &lt;dbl&gt;         &lt;dbl&gt;             &lt;dbl&gt;       &lt;dbl&gt;
1    30          61.5             5.75        2.40 
2   150          61.4             1.19        1.09 
3   500          61.4             0.350       0.592</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>mean estimate remains stable (61.5 [n=30], 61.4 [n=150] and n=500)</li>
<li>indicates the estimator stays centered near the population mean</li>
<li>as sample size increases <span class="math inline">\(\rightarrow\)</span> variance decreases from 5.75 to 0.350 and the standard deviation decreases from 2.40 to 0.592</li>
<li>estimates become more precise across repeated samples</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="summary">Summary</h3>
<div style="font-size:0.50em">
<ul>
<li>analysis examples discussed began defining a population quantity [parameter that cannot be directly observed</li>
<li>point estimate is a single numerical value computed from sample data to approximate that population parameter</li>
</ul>
<p>Common estimators include:</p>
<ul>
<li>sample mean → estimates population mean</li>
<li>sample proportion → estimates population prevalence</li>
</ul>
<p>Sampling distribution describes how an estimator behaves across repeated samples</p>
<ul>
<li>center → reflects bias (accuracy)</li>
<li>spread → reflects variance (precision)</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="summary-1">Summary</h3>
<div style="font-size:0.50em">
<ul>
<li><p>useful estimators generally have two properties:</p>
<ul>
<li><p>low bias [accuracy]</p>
<ul>
<li>estimator is centered near the true population parameter</li>
<li>example: repeated mean ≈ 61.4 with negligible bias</li>
</ul></li>
<li><p>low variance [precision]</p>
<ul>
<li>estimates vary minimally across repeated samples</li>
</ul></li>
</ul></li>
<li><p>bias can arise from systematic issues in data collection or sampling design</p>
<ul>
<li>precision improves with larger sample size</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="test_2_082025_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="test_2_082025_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>